const localTracks = [];
let trackIndex = -1;
let lyricsTargetIndex = -1;
let playing = false;
const $ = (selector) => document.querySelector(selector);
const audio = $('#audio-player');
const formatTime = (seconds) => Number.isFinite(seconds) ? `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}` : '0:00';
const toast = (message) => { const element = $('#toast'); element.textContent = message; element.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.remove('show'), 1800); };

function decodeId3Text(bytes, encoding = bytes[0]) { const content = bytes.slice(1); if (!content.length) return ''; if (encoding === 0) return new TextDecoder('latin1').decode(content).replace(/\0/g, '').trim(); if (encoding === 3) return new TextDecoder('utf-8').decode(content).replace(/\0/g, '').trim(); const charset = encoding === 1 && content[0] === 0xfe && content[1] === 0xff ? 'utf-16be' : 'utf-16le'; return new TextDecoder(charset).decode(content).replace(/\0/g, '').trim(); }
function synchsafe(bytes) { return ((bytes[0] & 0x7f) << 21) | ((bytes[1] & 0x7f) << 14) | ((bytes[2] & 0x7f) << 7) | (bytes[3] & 0x7f); }
async function readEmbeddedMetadata(file) { const bytes = new Uint8Array(await file.arrayBuffer()); const metadata = { title: file.name.replace(/\.[^.]+$/, ''), artist: '本地音乐', lyrics: '', coverUrl: '' }; if (new TextDecoder('latin1').decode(bytes.slice(0, 3)) !== 'ID3') return metadata; const version = bytes[3]; const end = Math.min(bytes.length, 10 + synchsafe(bytes.slice(6, 10))); for (let offset = 10; offset + 10 <= end;) { const id = new TextDecoder('latin1').decode(bytes.slice(offset, offset + 4)); const size = version === 4 ? synchsafe(bytes.slice(offset + 4, offset + 8)) : ((bytes[offset + 4] << 24) | (bytes[offset + 5] << 16) | (bytes[offset + 6] << 8) | bytes[offset + 7]) >>> 0; if (!id.trim() || !size || offset + 10 + size > end) break; const data = bytes.slice(offset + 10, offset + 10 + size); if (id === 'TIT2') metadata.title = decodeId3Text(data) || metadata.title; if (id === 'TPE1') metadata.artist = decodeId3Text(data) || metadata.artist; if (id === 'USLT') { const encoding = data[0]; let cursor = 4; while (cursor < data.length && (encoding ? data[cursor] || data[cursor + 1] : data[cursor])) cursor += encoding ? 2 : 1; metadata.lyrics = decodeId3Text(new Uint8Array([encoding, ...data.slice(cursor + (encoding ? 2 : 1))])); } if (id === 'APIC') { const encoding = data[0]; let cursor = 1; while (cursor < data.length && data[cursor]) cursor++; const mime = new TextDecoder('latin1').decode(data.slice(1, cursor)) || 'image/jpeg'; cursor += 2; while (cursor < data.length && (encoding ? data[cursor] || data[cursor + 1] : data[cursor])) cursor += encoding ? 2 : 1; cursor += encoding ? 2 : 1; if (cursor < data.length) metadata.coverUrl = URL.createObjectURL(new Blob([data.slice(cursor)], { type: mime })); } offset += 10 + size; } return metadata; }
function updatePlayState() { $('#play-toggle').textContent = playing ? 'Ⅱ' : '▶'; $('#expanded-play').textContent = playing ? 'Ⅱ' : '▶'; }
function setArtwork(url = '') { ['#open-player', '#expanded-art'].forEach((id) => { $(id).style.backgroundImage = url ? `url("${url}")` : ''; }); }
function setLyrics(lyrics) { const lines = lyrics ? lyrics.replace(/\[[\d:.]+\]/g, '').split(/\r?\n/).map((line) => line.trim()).filter(Boolean) : ['这首歌曲没有歌词。可在歌曲列表中点击“＋ 歌词”导入 LRC 文件。']; const box = $('#lyrics'); box.replaceChildren(...lines.map((line, index) => { const element = document.createElement('p'); element.textContent = line; if (lyrics && index === Math.min(2, lines.length - 1)) element.className = 'active-line'; if (!lyrics) element.className = 'empty-lyrics'; return element; })); }
function renderTracks() { const list = $('#local-list'); $('#local-empty').hidden = localTracks.length > 0; list.hidden = !localTracks.length; $('#local-description').textContent = localTracks.length ? `已导入 ${localTracks.length} 首本地音乐` : '从这台设备导入音乐文件，离线也能畅听。'; list.replaceChildren(...localTracks.map((track, index) => { const row = document.createElement('div'); row.className = `local-track${index === trackIndex ? ' current' : ''}`; row.tabIndex = 0; const name = document.createElement('div'); name.className = 'track-name'; name.innerHTML = '<span class="local-track-icon">♫</span>'; const title = document.createElement('b'); title.textContent = track.title; name.append(title); const artist = document.createElement('small'); artist.textContent = track.artist; const duration = document.createElement('time'); duration.textContent = track.duration; const action = document.createElement('button'); action.className = `lyrics-upload${track.lyrics ? ' has-lyrics' : ''}`; action.textContent = track.lyrics ? '歌词 ✓' : '＋ 歌词'; action.setAttribute('aria-label', `为 ${track.title} 添加 LRC 歌词`); action.addEventListener('click', (event) => { event.stopPropagation(); lyricsTargetIndex = index; $('#lrc-file').click(); }); row.append(name, artist, duration, action); row.addEventListener('click', () => playTrack(index)); row.addEventListener('keydown', (event) => { if (event.key === 'Enter') playTrack(index); }); return row; })); }
function playTrack(index) { const track = localTracks[index]; if (!track) return; trackIndex = index; audio.src = track.url; audio.play().then(() => { playing = true; updatePlayState(); }).catch(() => toast('浏览器阻止了播放，请再次点击播放按钮')); $('#now-title').textContent = track.title; $('#now-artist').textContent = track.artist; $('#expanded-title').textContent = track.title; $('#expanded-artist').textContent = track.artist; setArtwork(track.coverUrl); setLyrics(track.lyrics); renderTracks(); }
async function importFiles(files) { const audioFiles = [...files].filter((file) => file.type.startsWith('audio/') || /\.(mp3|m4a|wav|ogg|flac)$/i.test(file.name)); if (!audioFiles.length) return toast('请选择有效的音频文件'); for (const file of audioFiles) { const metadata = await readEmbeddedMetadata(file).catch(() => ({ title: file.name.replace(/\.[^.]+$/, ''), artist: '本地音乐', lyrics: '', coverUrl: '' })); const track = { ...metadata, url: URL.createObjectURL(file), duration: '加载中' }; localTracks.push(track); const probe = new Audio(track.url); probe.addEventListener('loadedmetadata', () => { track.duration = formatTime(probe.duration); renderTracks(); }, { once: true }); } renderTracks(); toast(`已导入 ${audioFiles.length} 首本地音乐`); }
function togglePlayer() { if (trackIndex < 0) return toast('请先导入并选择一首本地音乐'); if (audio.paused) audio.play().then(() => { playing = true; updatePlayState(); }); else { audio.pause(); playing = false; updatePlayState(); } }
function openPlayer() { $('#now-playing-view').classList.add('open'); $('#now-playing-view').setAttribute('aria-hidden', 'false'); $('#close-player').focus(); }
function closePlayer() { $('#now-playing-view').classList.remove('open'); $('#now-playing-view').setAttribute('aria-hidden', 'true'); }
$('#import-music').addEventListener('click', () => $('#music-files').click()); $('.import-link').addEventListener('click', () => $('#music-files').click()); $('#music-files').addEventListener('change', (event) => { importFiles(event.target.files); event.target.value = ''; }); $('#lrc-file').addEventListener('change', async (event) => { const [file] = event.target.files; if (!file || lyricsTargetIndex < 0) return; const lyrics = await file.text(); if (!lyrics.trim()) return toast('所选 LRC 文件为空'); localTracks[lyricsTargetIndex].lyrics = lyrics; if (lyricsTargetIndex === trackIndex) setLyrics(lyrics); renderTracks(); toast(`已为 ${localTracks[lyricsTargetIndex].title} 添加歌词`); event.target.value = ''; }); $('#play-toggle').addEventListener('click', togglePlayer); $('#expanded-play').addEventListener('click', togglePlayer); $('#previous').addEventListener('click', () => playTrack((trackIndex - 1 + localTracks.length) % localTracks.length)); $('#next').addEventListener('click', () => playTrack((trackIndex + 1) % localTracks.length)); $('#expanded-previous').addEventListener('click', () => $('#previous').click()); $('#expanded-next').addEventListener('click', () => $('#next').click()); $('#open-player').addEventListener('click', openPlayer); $('#open-lyrics').addEventListener('click', openPlayer); $('#close-player').addEventListener('click', closePlayer); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closePlayer(); });
audio.addEventListener('timeupdate', () => { ['#progress', '#expanded-progress'].forEach((id) => { $(id).max = audio.duration || 0; $(id).value = audio.currentTime; $(id).style.setProperty('--val', `${audio.duration ? audio.currentTime / audio.duration * 100 : 0}%`); }); $('#current-time').textContent = formatTime(audio.currentTime); $('#expanded-current-time').textContent = formatTime(audio.currentTime); }); audio.addEventListener('loadedmetadata', () => { $('#duration').textContent = formatTime(audio.duration); $('#expanded-duration').textContent = formatTime(audio.duration); }); audio.addEventListener('ended', () => $('#next').click()); ['#progress', '#expanded-progress'].forEach((id) => $(id).addEventListener('input', (event) => { audio.currentTime = Number(event.target.value); })); $('#volume').addEventListener('input', (event) => { audio.volume = event.target.value / 100; event.target.style.setProperty('--val', `${event.target.value}%`); }); $('#mute').addEventListener('click', () => { audio.muted = !audio.muted; }); $('#like').addEventListener('click', (event) => { event.currentTarget.textContent = event.currentTarget.textContent === '♡' ? '♥' : '♡'; }); $('#volume').dispatchEvent(new Event('input'));
